### ISSUE TITLE
Remove anything that has to do with previous Fig. 1

### ISSUE THREAD

**Issue by Nikoleta-v3** [drvinceknight/Evolutionary-game-theoretic-Model-of-Rhino-poaching#56]
>>> Ln 42 pg 3 of intro, it doesn't make sense to talk about quadrants without a figure to refer to with quadrants in it, or to say the poachers win (win at what).

Action: Reword this. It was left from removing Fig 1

**Comment by drvinceknight** [comment]
Related to #59: include figure so leave this text as was.

**Comment by Nikoleta-v3** [comment]
@drvinceknight  I apologise I forgot about this. Tamsin did not add the Figure in the commits so when I was reading through the paper it felt like the sentence had to removed. 

Should I undo the changes and add the Figure again?

**Comment by drvinceknight** [comment]
> Should I undo the changes and add the Figure again?

If you could that would be great @Nikoleta-v3, let me know when you have and I'll take it from there.

**Comment by Nikoleta-v3** [comment]
@drvinceknight this is done now!

**Comment by drvinceknight** [comment]
:1st_place_medal: :bowing_man:
