### ISSUE TITLE
[Not Addressable] Investigate if theoretical behaviour has been observed

### ISSUE THREAD

**Issue by Nikoleta-v3** [drvinceknight/Evolutionary-game-theoretic-Model-of-Rhino-poaching#57]
Do not spend too much time on this.

>>>The authors have also identified some situations were selective strategy could be more beneficial than indiscriminate. I think it could be interesting to look at the literature in which kind of situations we really are, and if these conditions found theoretically can be really encountered on the field.

**Comment by drvinceknight** [comment]
Have included a response to this in the response.
