### ISSUE TITLE
[Ask Tamsin] Understand comment by Reviewer 2

### ISSUE THREAD

**Issue by Nikoleta-v3** [drvinceknight/Evolutionary-game-theoretic-Model-of-Rhino-poaching#59]
>>> I think that a summary figure of the selected strategies (without discentive) could be also an interesting addition.

**Comment by TamsinELee** [comment]
I think this is essentially referring to the original Figure 1 we had - the pretty picture with rhinos that Anna Huzar did (this figure is still referred to in the introduction by the way - mentioning that the Lee et al. paper found their game settles in a quadrant - but there is not figure with a quadrant to refer to!).

So perhaps let's put that figure back in? It's a pretty figure, and considering it was requested...

**Comment by drvinceknight** [comment]
Putting the figure back in sounds good to me :+1:

**Comment by Nikoleta-v3** [comment]
This is addressed by #56
