### ISSUE TITLE
Address TODO in response.tex

### ISSUE THREAD

**Issue by Nikoleta-v3** [drvinceknight/Evolutionary-game-theoretic-Model-of-Rhino-poaching#74]

**Comment by Nikoleta-v3** [comment]
https://github.com/drvinceknight/Evolutionary-game-theoretic-Model-of-Rhino-poaching/blob/5299376902807bf0b35b54642e6e3e895a97a28b/response/main.tex#L255

**Comment by drvinceknight** [comment]
Closed by https://github.com/drvinceknight/Evolutionary-game-theoretic-Model-of-Rhino-poaching/commit/52a3878ae82dab81f9abcc1810ec2a69785934b7
